---
title: "Collabs Viz"
#bibliography: references.bib
author: "Bas Hofstra"
---



```{r, globalsettings, echo=FALSE, warning=FALSE, results='hide'}
library(knitr)

knitr::opts_chunk$set(echo = TRUE)
opts_chunk$set(tidy.opts=list(width.cutoff=100),tidy=TRUE, warning = FALSE, message = FALSE,comment = "#>", cache=TRUE, class.source=c("test"), class.output=c("test2"))
options(width = 100)
rgl::setupKnitr()



colorize <- function(x, color) {sprintf("<span style='color: %s;'>%s</span>", color, x) }

```

```{r klippy, echo=FALSE, include=TRUE}
klippy::klippy(position = c('top', 'right'))
#klippy::klippy(color = 'darkred')
#klippy::klippy(tooltip_message = 'Click to copy', tooltip_success = 'Done')
```

Last compiled on `r format(Sys.time(), '%B, %Y')`

<br>




Some packages necessary to run the analyses.

```{r packages}
rm(list = ls())
library("groundhog")
groundhog.library("
                  library('openxlsx')
                  library('flextable')
                  library('dplyr')
                  library('stringdist')
                  library('stringi')
                  library('stringr')
                  library('ggraph')
                  library('tidygraph')
                  library('igraph')
                  library('visNetwork')
                  library('gganimate')
                  library('shiny')
                  ", 
                  "2025-04-10")

```

# Data

Load the output data we generated before

```{r dataloading}
load("data/output_data/el_static.rda")
load("data/output_data/nodes_static.rda")
load("data/output_data/el_dyn1.rda")
load("data/output_data/el_dyn2.rda")
load("data/output_data/el_dyn3.rda")
load("data/output_data/el_dyn4.rda")
load("data/output_data/el_dyn5.rda")
load("data/output_data/el_dyn6.rda")
load("data/output_data/el_dyn7.rda")

```

# Standard Viz

Some starting viz.

```{r viz_static}

# gen graph
g <- graph_from_data_frame(edgelist1, directed = FALSE)

# add node characteristics fecundity (how many phds)
head(V(g)$name)
colnames(nodes)[1] <- "name"
V(g)$fec <- nodes$Freq[match(V(g)$name, nodes$name)]
head(V(g)$fec)

# generate the graph
ggraph(g, layout = "fr") +
  geom_edge_link(aes(width = n),
                 color = "grey50",
                 alpha = .5) +
  scale_edge_width(range = c(0.2, 3)) +
  geom_node_point(aes(size = fec),
                  color = "black",
                  fill = "steelblue",
                  shape = 21,
                  alpha = .9) +
  scale_size(range = c(3, 14)) +
  geom_node_text(aes(label = name),
                 repel = TRUE,
                 size = 3) +
  theme_void() +
  ggtitle("Supervisor collaborations: 1990-2025") +
      theme(
        plot.margin = margin(10, 10, 10, 10)
      )

```



# Nicer Viz

```{r viz_nicer}

# number of ties for info on hover
node_count <- degree(g)

# --- Nodes ---
nodes <- data.frame(
  id    = V(g)$name,
  label = "",
  value = V(g)$fec,
  title = sprintf(
    "<b>%s</b><br>PhDs: %s<br>Collabs: %s",
    V(g)$name,
    V(g)$fec,
    node_count
  ),
  stringsAsFactors = FALSE
)

# --- Edges ---
ed <- as_data_frame(g, what = "edges")
edges <- data.frame(
  from  = ed$from,
  to    = ed$to,
  value = ed$n,
  title = paste0("n: ", ed$n),
  stringsAsFactors = FALSE
)
library(htmltools)
# --- Plot ---
tagList(
  tags$h3(
    "Supervisor collaborations: 1990-2025",
    style = "
      font-family: Helvetica, Arial, sans-serif;
      font-weight: 600;
      margin-bottom: 10px;
    "
  ),
visNetwork(nodes, edges, height = "1000px", width = "100%") %>%
  visInteraction(hover = TRUE) %>%
  visOptions(highlightNearest = TRUE) %>%
  visEdges(smooth = FALSE) %>%
  visLayout(randomSeed = 42) %>%
  visPhysics(stabilization = TRUE) %>%
  visGroups(groupname = "default") %>%
  htmlwidgets::onRender("
    function(el) {
      el.style.background = '#ffffff';
      el.style.borderRadius = '14px';
      el.style.boxShadow = '0 12px 35px rgba(0,0,0,0.18)';
      el.style.padding = '10px';
      el.style.border = '1px solid #e6e6e6';
    }
  ")
)
```

# Dynamic viz

```{r viz_dyn}

edges_all <- bind_rows(
  t1 %>% mutate(time = "t1"),
  t2 %>% mutate(time = "t2"),
  t3 %>% mutate(time = "t3"),
  t4 %>% mutate(time = "t4"),
  t5 %>% mutate(time = "t5"),
  t6 %>% mutate(time = "t6"),
  t7 %>% mutate(time = "t7")
)

# edges_all must have: from, to, n, time

# 1) Nodes and fixed layout from union graph
nodes <- sort(unique(c(edges_all$from, edges_all$to)))

g_all <- graph_from_data_frame(
  edges_all %>% distinct(from, to),
  directed = FALSE,
  vertices = data.frame(name = nodes)
)

xy <- layout_with_fr(g_all)  # or layout_with_kk(g_all)
nodes_df <- data.frame(
  name = V(g_all)$name,
  x = xy[, 1],
  y = xy[, 2]
)

# 2) Edge coordinates per time
edges_df <- edges_all %>%
  left_join(nodes_df, by = c("from" = "name")) %>%
  rename(x1 = x, y1 = y) %>%
  left_join(nodes_df, by = c("to" = "name")) %>%
  rename(x2 = x, y2 = y)

# 3) Plot + animate
p <- ggplot() +
  geom_segment(
    data = edges_df,
    aes(x = x1, y = y1, xend = x2, yend = y2, linewidth = n),
    alpha = 0.45,
    colour = "grey60"
  ) +
  geom_point(
    data = nodes_df,
    aes(x = x, y = y),
    size = 2
  ) +
  scale_linewidth(range = c(0.2, 3)) +
  coord_equal() +
  theme_void() +
  labs(title = "Time: {closest_state}") +
  transition_states(time, state_length = 1) +
  ease_aes("linear")

anim <- animate(p, fps = 10, width = 900, height = 700)
anim

```

# Shiny viz

```{r shiny, eval = FALSE}


# ensure time is ordered t1 < t2 < ... < t7
times <- sort(unique(edges_all$time))
edges_all <- edges_all %>%
  mutate(time = factor(time, levels = times, ordered = TRUE))

all_nodes <- sort(unique(c(edges_all$from, edges_all$to)))

ui <- fluidPage(
  sliderInput("tt", "Time", min = 1, max = length(times), value = 1, step = 1,
              animate = TRUE),
  visNetworkOutput("net", height = "85vh")
)

server <- function(input, output, session) {

  output$net <- renderVisNetwork({

    # cumulative edges up to selected time
    ed_cum <- edges_all %>%
      filter(time <= times[input$tt]) %>%
      group_by(from, to) %>%
      summarise(n = max(n), .groups = "drop")   # keep strongest (or use sum(n) / last(n))

    g_t <- graph_from_data_frame(ed_cum, directed = FALSE,
                                vertices = data.frame(name = all_nodes))

    nodes_v <- data.frame(
      id    = V(g_t)$name,
      label = "",            # no labels on canvas
      title = V(g_t)$name    # hover shows label
    )

    e <- as_data_frame(g_t, what = "edges")
    edges_v <- data.frame(
      from  = e$from,
      to    = e$to,
      value = e$n,                 # edge width
      title = paste0("n: ", e$n)   # hover edge shows n
    )

    visNetwork(nodes_v, edges_v) %>%
      visInteraction(hover = TRUE) %>%
      visOptions(highlightNearest = TRUE) %>%
      visEdges(smooth = FALSE) %>%
      visLayout(randomSeed = 42)
  })
}

shinyApp(ui, server)

```